name: "Format Queries"
on: workflow_dispatch 

jobs:
  test: # make sure the action works on a clean machine without building
    name: Run auto formatter
    runs-on: ubuntu-latest

    steps:
        - name: Check out Git repository
          uses: actions/checkout@v2

        - name: Install zetasql
          run: |
              wget https://github.com/Matts966/zetasql-formatter/releases/latest/download/zetasql-formatter_linux_x86_64.zip
              sudo unzip zetasql-formatter_linux_x86_64.zip -d /usr/local/bin
              rm zetasql-formatter_linux_x86_64.zip

        - name: SQLAutoFormatter
          uses: yoheikikuta/sql-autoformat-action@v1.0.2
          with:
            github_token: ${{ secrets.SQLFORMATTER }}
            path: "./Scripts/SQL/"
        
        - name: Sql-Lint
          uses: Bidaya0/sql-lint-in-action@v0.0.2
          with:
            path: "./Scripts/SQL/"
